version: "2"

run:
  timeout: 5m
  modules-download-mode: readonly

linters:
  default: none
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - unused
    - goimports
    - gosec
    - dupl
    - noctx
    - bodyclose
    - prealloc
    - unconvert
    - misspell

linters-settings:
  dupl:
    threshold: 150
  govet:
    enable-all: true
  goimports:
    local-prefixes: github.com/hassan123789/go-ai-agent
  misspell:
    locale: US

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - dupl
        - gosec
    - path: cmd/
      linters:
        - noctx

output:
  formats:
    text:
      path: stdout
      print-linter-name: true
      print-issued-lines: true
