version: "2"

run:
  timeout: 5m
  modules-download-mode: readonly

linters:
  default: none
  enable:
    - errcheck
    - govet
    - ineffassign
    - staticcheck
    - unused
    - gosec
    - dupl
    - noctx
    - bodyclose
    - prealloc
    - unconvert
    - misspell
  settings:
    dupl:
      threshold: 150
    govet:
      enable-all: true
      disable:
        - fieldalignment
    misspell:
      locale: US
  exclusions:
    rules:
      - path: _test\.go
        linters:
          - dupl
          - gosec
      - path: cmd/
        linters:
          - noctx

formatters:
  enable:
    - goimports
  settings:
    goimports:
      local-prefixes:
        - github.com/hassan123789/go-ai-agent

output:
  formats:
    text:
      path: stdout
      print-linter-name: true
      print-issued-lines: true
